### ISSUE TITLE
Feature: Option to generate machine readable reports

### ISSUE THREAD

**Issue by vitonsky** [azat-io/todoctor#1]
Add option to generate machine readable reports (json/txt or something).

CLI tools are useful to run on CI actions. It would be nice to generate report with your tool, then process some JSON file and add comment with diff and warnings by some custom logic.

Custom logic may be implemented on specific project side, but this tool must provide feature to generate machine readable report

**Comment by azat-io** [comment]
Yes, that's a good idea. Perhaps we should add a `--report-type` option with the value `json` or `html`.
Thank you for your issue!

**Comment by azat-io** [comment]
Added in a7e9baa2fdfede79911a87da39e00a8a3a00fa5d.
Released in [v1.1.0](https://github.com/azat-io/todoctor/releases/tag/v1.1.0).
